import Head from "next/head";
import { Welcome } from "@/components/Welcome";
import { User } from "@/components/User";
import { Parent } from "@/components/Parent";
import { Descriptions } from "@/components/Descriptions";
import { Dog } from "@/components/Dog";
import { Counter } from "@/components/Counter";
import { Counter2 } from "@/components/Counter2";
import { TrafficLight } from "@/components/TrafficLight";
import { Form } from "@/components/FormCadastro";
import { TaskList } from "@/components/TaskList";

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <h1>Hello world!</h1>
                {/* Chamando o componente */}
                <Welcome />
                {/* Chamando o componente com expressão JSX */}
                <User />
                {/* Componente pai que possue um cmponente filho incorporado */}
                <Parent />
                {/* Chamando o componente passando props */}
                <Descriptions name="Leandro" age="19" />
                {/* Chamando o componente que usa desestruturação passando props  */}
                <Dog name="Rex" breed="Pitibull" />
                {/* Chamando contador */}
                <Counter />
                <Counter2 />
                <TrafficLight />
                <br />
                <br />
                <Form />

                <br />
                <br />
                {/* Passando a lista de tarefas por props */}
                <TaskList
                    tasks={[
                        {
                            id: 1,
                            title: "Estudar React",
                        },
                        {
                            id: 2,
                            title: "Pagar boletos",
                        },
                        {
                            id: 3,
                            title: "Retirar o lixo",
                        },
                        {
                            id: 4,
                            title: "Lavar roupa",
                        },
                    ]}
                />
            </main>
        </>
    );
}
